const articles=[
 {title:'Build a smarter home without turning it into a science project',cat:'Smart Home',id:'article-smart-home',desc:'A practical roadmap for choosing the right devices, ecosystems and automations — without buying everything at once.'},
 {title:'5 smart-home upgrades that make a real difference',cat:'Security',id:'article-security',desc:'The upgrades that improve convenience and peace of mind without creating unnecessary complexity.'},
 {title:'The everyday tech essentials we keep reaching for',cat:'Gadgets',id:'article-gadgets',desc:'Useful technology that earns its place because it solves small problems every single day.'},
 {title:'Where useful AI gadgets are heading next',cat:'AI & Future Tech',id:'article-ai',desc:'A grounded look at consumer AI hardware and the features that may actually matter.'},
 {title:'Best smart-home devices for beginners',cat:'Buying Guides',id:'guide-beginners',desc:'Start small, stay compatible and build a system you will actually use.'},
 {title:'Best tech gadgets under $100',cat:'Buying Guides',id:'guide-under100',desc:'Useful upgrades that balance price, quality and everyday value.'},
 {title:'How to choose a smart doorbell',cat:'Buying Guides',id:'guide-doorbell',desc:'Video, storage, subscriptions, privacy and installation explained.'},
 {title:'How to build your first smart home',cat:'How-To',id:'how-smart-home',desc:'A beginner-friendly path from one useful device to a connected home.'},
 {title:'How to secure connected devices',cat:'How-To',id:'how-security',desc:'Simple privacy and security habits for a connected home.'},
 {title:'How to automate daily routines',cat:'How-To',id:'how-automation',desc:'Turn repetitive tasks into simple routines you barely notice.'}
];
const toast=document.getElementById('toast');function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
document.getElementById('announcementClose')?.addEventListener('click',()=>document.querySelector('.announcement').remove());
const menu=document.getElementById('mobileMenu');document.getElementById('menuOpen')?.addEventListener('click',()=>{menu.classList.toggle('open');menu.style.display=menu.classList.contains('open')?'flex':'none'});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.style.display='none';menu.classList.remove('open')}));
const overlay=document.getElementById('searchOverlay');document.getElementById('searchOpen')?.addEventListener('click',()=>{overlay.classList.add('open');document.getElementById('siteSearch').focus()});document.getElementById('searchClose')?.addEventListener('click',()=>overlay.classList.remove('open'));overlay?.addEventListener('click',e=>{if(e.target===overlay)overlay.classList.remove('open')});
const search=document.getElementById('siteSearch');const results=document.getElementById('searchResults');function renderSearch(q=''){const term=q.trim().toLowerCase();if(!term){results.innerHTML='<div class="search-empty">Try “smart security”, “gadgets”, “reviews” or “buying guides”.</div>';return}const matches=articles.filter(a=>(a.title+' '+a.cat+' '+a.desc).toLowerCase().includes(term));results.innerHTML=matches.length?matches.map(a=>`<a class="search-result" href="#${a.id}"><strong>${a.title}</strong><small>${a.cat} · ${a.desc}</small></a>`).join(''):'<div class="search-empty">No stories found. Try another search.</div>'}search?.addEventListener('input',e=>renderSearch(e.target.value));renderSearch();
document.getElementById('newsletterForm')?.addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('email').value;if(email)showToast('Thanks — you’re on the list. Welcome to the weekly edit!');e.target.reset()});
document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#article-"],a[href^="#guide-"],a[href^="#how-"]');if(!link)return;const item=articles.find(a=>a.id===link.getAttribute('href').slice(1));if(item){e.preventDefault();openArticle(item)}});
function openArticle(item){const existing=document.getElementById('articleModal');if(existing)existing.remove();const modal=document.createElement('div');modal.id='articleModal';modal.className='search-overlay open';modal.innerHTML=`<button class="search-close" aria-label="Close">×</button><article class="article-modal"><span class="eyebrow">${item.cat.toUpperCase()}</span><h2>${item.title}</h2><p class="article-lead">${item.desc}</p><div class="article-meta">Updated August 21, 2026 · 7 min read</div><hr><p>Technology should solve problems, not create more of them. In this guide, we break the topic into the decisions that matter most, explain the trade-offs in plain English, and show you where to start.</p><h3>Start with the problem</h3><p>Before choosing a device, decide what you want to improve: convenience, security, comfort, entertainment, energy use or productivity. The best setup is the one that fits your routine.</p><h3>Look for compatibility</h3><p>Check the ecosystem, connectivity standards, app quality, privacy controls and whether important features require an ongoing subscription.</p><h3>Buy for the next three years</h3><p>A good purchase should remain useful as your setup grows. Favor reliable hardware, clear software support and products with a sensible upgrade path.</p><div class="modal-callout"><strong>Our approach</strong><span>Clear explanations. Practical recommendations. No unnecessary hype.</span></div><button class="btn btn-primary modal-close">Back to the site</button></article>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.search-close').addEventListener('click',close);modal.querySelector('.modal-close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()})}
document.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{if(a.getAttribute('href')?.startsWith('#'))history.replaceState(null,'',a.getAttribute('href'))}));
const extra=document.createElement('style');extra.textContent='.mobile-menu.open{display:flex;flex-direction:column;padding:12px 20px 20px;border-top:1px solid #edf0f3;gap:12px;font-size:13px;font-weight:700}.article-modal{width:min(820px,calc(100% - 32px));max-height:78vh;overflow:auto;background:#fff;color:#132033;border-radius:22px;padding:42px;box-shadow:0 30px 90px #0008}.article-modal h2{font:700 clamp(32px,5vw,54px)/1.08 "Space Grotesk";letter-spacing:-.04em;margin:12px 0}.article-lead{font-size:17px;color:#68798a;max-width:700px}.article-meta{font-size:10px;color:#8a98a7;margin:18px 0}.article-modal hr{border:0;border-top:1px solid #e8edf2;margin:25px 0}.article-modal p{font-size:14px;color:#5f7081}.article-modal h3{font:600 22px "Space Grotesk";margin-top:28px}.modal-callout{display:flex;gap:14px;flex-direction:column;background:#edf9fd;border-left:3px solid #0ba6d8;padding:18px;border-radius:10px;margin:25px 0}.modal-callout strong{font:700 14px "Space Grotesk"}.modal-callout span{font-size:12px;color:#637487}@media(max-width:600px){.article-modal{padding:26px 20px;max-height:82vh}.article-modal h2{font-size:32px}}';document.head.appendChild(extra);
